#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

dir_length = 1

[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "HOME"
path = "~/"

[[session]]
name = "RYZEN9-7950X"
startup_command = "sshr"

[[session]]
name = "TSPROXY"
startup_command = "ssh tsproxy"

[[session]]
name = "VOYAGER-1"
startup_command = "ssh voyager-1 tmux new-session -A -s main"

[[session]]
name = "PORTFOLIO"
path = "~/Developer/portfolio/"

[[session]]
name = "LATTICA"
path = "~/Developer/lattica/"

[[session]]
name = "HARVESTLOG"
path = "~/Developer/harvestlog/"

[[session]]
name = "UBERTRAGEN"
path = "~/Ubertragen/"

[[session]]
name = "PHYT.FUN"
path = "~/Developer/phyt.fun"

[[session]]
name = "NEOVIM"
path = "~/.config/nvim"

[[session]]
name = "ANVIL"
path = "~/Developer/lattica/"
startup_command = "anvil"

[[wildcard]]
pattern = "~/Developer/lattica/**"
startup_command = "sh -c 'tmux rename-session \"$(basename \"{}\" | tr \"[:lower:]\" \"[:upper:]\")\" >/dev/null 2>&1; clear; exec ${SHELL:-/bin/bash} -l'"

[[wildcard]]
pattern = "~/Developer/*"
disable_startup_command = true
