return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  lazy = false,
  priority = 1000,
  opts = {
    ensure_installed = {
      "bash",
      "css",
      "dockerfile",
      "go",
      "gomod",
      "terraform",
      "hcl",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "nix",
      "nginx",
      "python",
      "regex",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
      "templ",
      "latex",
    },
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { "latex" },
    },
    indent = { enable = true },
  },
}
