---@type LazySpec
return {
  -- {
  "mikavilpas/yazi.nvim",
  enabled = false,
  --   version = "*", -- use the latest stable version
  --   event = "VeryLazy",
  --   dependencies = {
  --     { "nvim-lua/plenary.nvim", lazy = true },
  --   },
  --   keys = {
  --     {
  --       "<leader>e",
  --       "<cmd>Yazi cwd<cr>",
  --       desc = "Open the file manager in nvim's working directory",
  --     },
  --     {
  --       "<leader>E",
  --       "<cmd>Yazi cwd<cr>",
  --       desc = "Open the file manager in nvim's working directory",
  --     },
  --     {
  --       "<c-up>",
  --       "<cmd>Yazi toggle<cr>",
  --       desc = "Resume the last yazi session",
  --     },
  --   },
  --   ---@type YaziConfig | {}
  --   opts = {
  --     -- the type of border to use for the floating window. Can be many values,
  --     -- including 'none', 'rounded', 'single', 'double', 'shadow', etc. For
  --     -- more information, see :h nvim_open_win
  --     yazi_floating_window_border = "rounded",
  --     -- the floating window scaling factor. 1 means 100%, 0.9 means 90%, etc.
  --     floating_window_scaling_factor = 0.75,
  --     -- the transparency of the yazi floating window (0-100). See :h winblend
  --     yazi_floating_window_winblend = 10,
  --     -- highlight buffers in the same directory as the hovered buffer
  --     highlight_hovered_buffers_in_same_directory = false,
  --     -- if you want to open yazi instead of netrw, see below for more info
  --     open_for_directories = true,
  --     keymaps = {
  --       show_help = "<f1>",
  --       open_file_in_vertical_split = "<Space>v",
  --     },
  --   },
  --   -- 👇 if you use `open_for_directories=true`, this is recommended
  --   init = function()
  --     -- mark netrw as loaded so it's not loaded at all.
  --     --
  --     -- More details: https://github.com/mikavilpas/yazi.nvim/issues/802
  --     vim.g.loaded_netrwPlugin = 1
  --   end,
  -- },
  -- {
  --   -- example: include a flavor
  --   dir = "~/.config/yazi/flavors/anysphere.yazi/",
  --   lazy = false,
  --   build = function(plugin)
  --     require("yazi.plugin").build_flavor(plugin)
  --   end,
  -- },
}
